{{ if .Values.restore.destination.mongodb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.job.name}}-dumbster-mongodb-restore
spec:
  ttlSecondsAfterFinished: {{.Values.job.ttlSecondsAfterFinished}}
  backoffLimit: {{.Values.job.backoffLimit}}
  parallelism: 1
  template:
    spec:
      containers:
      - name: dumpster
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{.Values.image.imagePullPolicy}}
        env:
        - name: DUMPSTER_METHOD
          value: restore
        - name: DUMPSTER_DBMS
          value: mongodb

        - name: DUMPSTER_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{.Values.restore.destination.mongodb.secretName}}
              key: connectionString

        - name: DUMPSTER_RESTORE_FILES
          value: {{.Values.restore.destination.mongodb.restoreFile}}

        - name: DUMPSTER_MOUNT_PATH
          value: {{.Values.restore.source.azureFile.mountPath}}
        - name: IS_COSMOS_DB
          value: {{.Values.restore.destination.mongodb.cosmosDB | quote}}
        volumeMounts: 
          - name: backup-storage
            mountPath: {{.Values.restore.source.azureFile.mountPath}}
      volumes: 
        - name: backup-storage
          azureFile:
            secretName: {{ .Values.restore.source.azureFile.secretName }}
            shareName: {{ .Values.restore.source.azureFile.shareName }}
            readOnly: {{ .Values.restore.source.azureFile.readOnly }}
      restartPolicy: Never
{{ end }}
