{{ if .Values.restore.destination.postgres.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: dumbster-postgresql-restore
spec:
  # ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: dumpster
        image: "{{ .Values.images.repository }}:{{ .Values.images.tag }}"
        imagePullPolicy: {{.Values.image.imagePullPolicy}}
        env:
        - name: DUMPSTER_METHOD
          value: restore
        - name: DUMPSTER_DBMS
          value: pgsql

        - name: DUMPSTER_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: {{.Values.restore.destination.postgres.secretName}}
              key: connectionString

        - name: DUMPSTER_RESTORE_FILES
          value: {{.Values.restore.destination.postgres.restoreFile}}

        - name: DUMPSTER_MOUNT_PATH
          value: {{.Values.restore.source.azureFile.mountPath}}

        volumeMounts:
          - name: backup-storage
            mountPath: {{.Values.restore.source.azureFile.mountPath}}
      volumes: 
        - name: backup-storage
          azureFile:
            secretName: {{ .Values.restore.source.azureFile.secretName }}
            shareName: {{ .Values.restore.source.azureFile.shareName }}
            readOnly: {{ .Values.restore.source.azureFile.readOnly }}
      restartPolicy: Never
{{ end }}
