apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}-deployment
  labels:
    name: {{.Chart.Name}}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      labels:
        app: posts-service
    spec:
      containers:
      - name: posts-service
        image: sondregj/posts-service:latest
        ports:
        - containerPort: 80
        env:
        - name: PG_USER
          valueFrom:
            secretKeyRef: 
              name: {{ .Values.postgres.secretName }}
              key: user
        - name: PG_HOST
          valueFrom:
            secretKeyRef: 
              name: {{ .Values.postgres.secretName }}
              key: host
        - name: PG_DATABASE
          valueFrom:
            secretKeyRef: 
              name: {{ .Values.postgres.secretName }}
              key: database
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: {{ .Values.postgres.secretName }}
              key: password

        - name: PG_PORT
          value: {{.Values.postgres.port}}
