apiVersion: v1
kind: Service
metadata:
  name: posts-service-svc
  labels:
    name: posts-service-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: posts-service
