image:
  repository: sondregj/dumbster
  tag: latest
  pullPolicy: IfNotPresent

job:
  name: ""
  ttlSecondsAfterFinished: 180
  backoffLimit: 1

backup:
  enabled: false

  schedule: "@daily"
  retentionDays: 30

  source:
    postgres:
      enabled: false
      databases: []
      secretName: dumbster-secret-postgres # connectionString

    mongodb:
      enabled: false
      secretName: dumbster-secret-mongodb

    azureFile:
      enabled: false
      secretName: dumbster-secret-azurefile

  destination:
    azureFile:
      # enabled: false
      mountPath: "/"
      secretName: dumbster-secret-azurefile-backup
      shareName: dumbster-azurefile-sharename
      readOnly: false

restore:
  enabled: false
  
  source:
    azureFile:
      mountPath: "/"
      secretName: dumbster-secret-azurefile-backup
      shareName: dumbster-azurefile-sharename
      readOnly: false

  destination:
    postgres:
      enabled: false
      secretName: ""
      restoreFile: ""
    azureFile:
      enabled: false
      secretName: ""
    mongodb:
      enabled: false
      secretName: ""
      restoreFile: ""
      cosmosDB: false
    