# replicaCount: 1

image:
  repository: sondregj/dumbster
  pullPolicy: IfNotPresent

job:
  name: ""

backup:
  enabled: false

  schedule: "@daily"
  retentionDays: 30

  source:
    postgres:
      enabled: false
      secrets:
      valueFrom:
        secretKeyRef:
          name: ""
          key: ""

    mongodb:
      enabled: false

    blobStorage:
      enabled: false

  destination:
    azureFile:
      enabled: false
      mountPath: "/"
      secretName: {{ .Values.api.azureFile.secretName }}
      shareName: {{ .Values.api.azureFile.shareName }}
      readOnly: {{ .Values.api.azureFile.readOnly }}

restore:
  enabled: false
  
  source:
    azureFile:
      mountPath: "/"
      secretName: {{ .Values.api.azureFile.secretName }}
      shareName: {{ .Values.api.azureFile.shareName }}
      readOnly: {{ .Values.api.azureFile.readOnly }}

  destination:
    postgres:
      enabled: false
    blob-storage:
      enabled: false
    mongodb:
      enabled: false
    