apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{.Values.job.name}}-dumbster-blob-storage-backup
spec:
  schedule: {{.Values.backup.schedule}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dumbster
            image: sondregj/dumbster:latest
            imagePullPolicy: Always
            env:
            - name: DUMPSTER_METHOD
              value: dump

            - name: DUMPSTER_DBMS
              value: blob-storage

            - name: DUMPSTER_BACKUPS_MAX_AGE
              value: {{.Values.backup.retention-days}}

            - name: DUMPSTER_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: dumpster-secret
                  key: ""

            volumeMounts: []
          volumes: []
          restartPolicy: Never