apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{.Values.job.name}}-dumbster-mongodb-backup
spec:
  schedule: {{.Values.backup.schedule}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dumbster
            image: sondregj/dumbster:latest
            imagePullPolicy: Always
            env:

            - name: DUMPSTER_METHOD
              value: dump

            - name: DUMPSTER_DBMS
              value: mongodb

            - name: DUMPSTER_BACKUPS_MAX_AGE
              value: {{.Values.backup.retention-days}}

            - name: DUMPSTER_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: dumpster-secret
                  key: dumpster_connection_string

            - name: DUMPSTER_MOUNT_PATH
              valueFrom:
                secretKeyRef:
                  name: dumpster-secret
                  key: dumpster_mount_path

            volumeMounts: []
          volumes: []
          restartPolicy: Never

