{{ if .Values.backup.source.mongodb.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{.Values.job.name}}-dumbster-mongodb-backup
spec:
  schedule: {{.Values.backup.schedule | quote}}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{.Values.job.ttlSecondsAfterFinished}}
      backoffLimit: {{.Values.job.backoffLimit}}
      template:
        spec:
          containers:
          - name: dumbster
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{.Values.image.pullPolicy}}

            env:
            - name: DUMPSTER_METHOD
              value: dump
            - name: DUMPSTER_DBMS
              value: mongodb

            - name: DUMPSTER_BACKUPS_MAX_AGE
              value: {{.Values.backup.retentionDays | quote}}
            - name: DUMPSTER_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{.Values.backup.source.mongodb.secretName}}
                  key: connectionString

            - name: DUMPSTER_MOUNT_PATH
              value: {{.Values.backup.destination.azureFile.mountPath}}

            volumeMounts: 
              - name: backup-storage
                mountPath: {{.Values.backup.destination.azureFile.mountPath}}
          volumes: 
            - name: backup-storage
              azureFile:
                secretName: {{ .Values.backup.destination.azureFile.secretName }}
                shareName: {{ .Values.backup.destination.azureFile.shareName }}
                readOnly: {{ .Values.backup.destination.azureFile.readOnly }}
          restartPolicy: Never

{{ end }}
