{{ if .Values.backup.postgres.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{.Values.job.name}}-dumbster-postgres-backup
spec:
  schedule: {{.Values.backup.schedule}}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dumbster
            image: sondregj/dumbster:latest
            imagePullPolicy: Always
            env:
            - name: DUMPSTER_METHOD
              value: dump
            - name: DUMPSTER_DBMS
              value: pgsql
            - name: DUMPSTER_BACKUPS_MAX_AGE
              value: {{.Values.backup.retentionDays}}
            - name: DUMPSTER_CONNECTION_STRING
              valueFrom:
                secretKeyRef: {{.Values.backup.postgres.valueFrom.secretKeyRef}}
            - name: DUMPSTER_DATABASES
              value: {{.Values.backup.postgres.databases}}
            
            - name: DUMPSTER_MOUNT_PATH
              value: {{.Values.backup.destination.azureFile.mountPath}}

            volumeMounts: 
              - name: backup-storage
                mountPath: {{.Values.backup.destination.azureFile.mountPath}}
          volumes: 
            - name: backup-storage
              azureFile:
                secretName: {{ .Values.backup.destination.azureFile.secretName }}
                shareName: {{ .Values.backup.destination.azureFile.shareName }}
                readOnly: {{ .Values.backup.destination.azureFile.readOnly }}
          restartPolicy: Never
{{ end }}
