name: Helm Chart Releaser

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Helm Chart Releaser
      uses: helm/chart-releaser-action@v1.0.0-alpha.2
      with:
        # The chart-releaser version to use (default: v0.2.3)
        # version: # optional
        
        # The charts directory
        charts_dir: charts # optional, default is charts
        
        # The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)
        charts_repo_url: https://charts.sondregjellestad.space
